### ISSUE TITLE
error in version numbering?

### ISSUE THREAD

**Issue by honeypot92** [looms-polimi/Parallel_manipulators#3]
Hello,

I am Phd candidate working with Benjamin Boudon.

Your latest version 1.0.2 is on same commit as the version 1.0.1. Is there any error in this numbering?
I downloaded the latest version and tested on Dymola, the relative path for TorqueCommand.txt is corrected, but the RealOut connectors are still present in poseMux models.
And also, the Dymola recognizes the new latest version as 1.0.1 not 1.0.2 when I imported it.

Thank you for revising this issue.

Best regards,
Hyunjun BAE

hyun_jun.bae@sigma-clermont.fr

**Comment by casella** [comment]
Sorry, I had a fix in the repo on my PC and I forgot to push it on GitHub before making the release. 1.0.2 should now have the connector fix.
